http:
  routers:
    app-example:
      rule: "Host(`app.example.com`)"
      entryPoints: [https]
      service: app-example
      middlewares: [app-security]
      tls:
        certResolver: cloudflare

    root-domain:
      rule: "Host(`example.com`)"
      entryPoints: [https]
      service: dummy
      middlewares: [root-security]
      tls:
        certResolver: cloudflare

  services:
    app-example:
      loadBalancer:
        servers:
          - url: "http://your-app-server:port"
        passHostHeader: true

    dummy:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9999"
        passHostHeader: false

  middlewares:
    rate-limit:
      rateLimit:
        average: 100
        period: 1s
        burst: 200
        sourceCriterion:
          ipStrategy:
            depth: 1
            excludedIPs:
              - "127.0.0.1/32"
              - "10.0.0.0/8"

    crowdsec-bouncer:
      plugin:
        crowdsec-bouncer-traefik-plugin:
          enabled: true
          logLevel: INFO
          crowdsecMode: stream
          crowdsecLapiKey: "your_crowdsec_api_key_here"
          crowdsecLapiScheme: http
          crowdsecLapiHost: "crowdsec:8080"
          crowdsecLapiPath: "/"
          defaultDecisionSeconds: 300
          httpTimeoutSeconds: 10
          updateIntervalSeconds: 60
          crowdsecAppsecEnabled: false
          crowdsecAppsecFailureBlock: true
          crowdsecAppsecUnreachableBlock: true
          clientTrustedIPs:
            - "10.0.0.0/8"
            - "172.16.0.0/12"
            - "192.168.0.0/16"
          forwardedHeadersCustomName: "X-Forwarded-For"

    app-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          Strict-Transport-Security: "max-age=63072000; includeSubDomains; preload"
          X-Frame-Options: "SAMEORIGIN"
          X-Content-Type-Options: "nosniff"
          X-XSS-Protection: "1; mode=block"
          Referrer-Policy: "same-origin"
          Permissions-Policy: "geolocation=(), microphone=(), camera=()"

    root-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          Strict-Transport-Security: "max-age=63072000; includeSubDomains; preload"
          X-Frame-Options: "SAMEORIGIN"
          X-Content-Type-Options: "nosniff"
          X-XSS-Protection: "1; mode=block"
          Referrer-Policy: "same-origin"
          Permissions-Policy: "geolocation=(), microphone=(), camera=()"
          Content-Security-Policy: "default-src 'self'"

    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

    app-security:
      chain:
        middlewares:
          - crowdsec-bouncer
          - rate-limit
          - app-headers

    root-security:
      chain:
        middlewares:
          - crowdsec-bouncer
          - rate-limit
          - root-headers
          - https-redirect
