http:
  routers:
    nextcloud:
      rule: "Host(`cloud.facuint.org`) || Host(`ncloud.facuint.org`)"
      entryPoints: [https]
      service: nextcloud
      middlewares: [nextcloud-security]
      tls:
        certResolver: cloudflare

    root-domain:
      rule: "Host(`facuint.org`)"
      entryPoints: [https]
      service: dummy
      middlewares: [root-security]
      tls:
        certResolver: cloudflare

  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://10.0.0.16"
        passHostHeader: true
        healthCheck:
          path: "/status.php"
          interval: "30s"
          timeout: "5s"

    dummy:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9999"
        passHostHeader: false

  middlewares:
    rate-limit:
      rateLimit:
        average: 100
        period: 1s
        burst: 200
        sourceCriterion:
          ipStrategy:
            depth: 1
            excludedIPs:
              - "127.0.0.1/32"
              - "10.0.0.0/8"

    crowdsec-bouncer:
      plugin:
        crowdsec-bouncer-traefik-plugin:
          enabled: true
          logLevel: INFO
          crowdsecMode: stream
          crowdsecLapiKey: "Yy6yhGwQzx6TFb/PJo/TXoIbDIRvK644q7nlOAHFs3U"
          crowdsecLapiScheme: http
          crowdsecLapiHost: "crowdsec:8080"
          crowdsecLapiPath: "/"
          defaultDecisionSeconds: 300
          httpTimeoutSeconds: 10
          updateIntervalSeconds: 60
          crowdsecAppsecEnabled: false
          crowdsecAppsecFailureBlock: true
          crowdsecAppsecUnreachableBlock: true
          clientTrustedIPs:
            - "10.0.0.0/8"
            - "172.16.0.0/12"
            - "192.168.0.0/16"
            - "186.6.141.57/32"
            - "179.52.191.96/32"
            - "186.6.0.0/15"
            - "179.52.0.0/15"
          forwardedHeadersTrustedIPs:
            - "173.245.48.0/20"
            - "103.21.244.0/22"
            - "141.101.64.0/18"
            - "108.162.192.0/18"
            - "162.158.0.0/15"
            - "104.16.0.0/13"
            - "172.64.0.0/13"
          forwardedHeadersCustomName: "X-Forwarded-For"

    nextcloud-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          Strict-Transport-Security: "max-age=63072000; includeSubDomains; preload"
          Permissions-Policy: "geolocation=(), microphone=(), camera=(), payment=(), fullscreen=(self), autoplay=(self)"
          X-Frame-Options: "SAMEORIGIN"
          X-Content-Type-Options: "nosniff"
          X-XSS-Protection: "1; mode=block"
          Referrer-Policy: "same-origin"
          Feature-Policy: ""
          Server: ""

    root-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          Strict-Transport-Security: "max-age=63072000; includeSubDomains; preload"
          X-Frame-Options: "SAMEORIGIN"
          X-Content-Type-Options: "nosniff"
          X-XSS-Protection: "1; mode=block"
          Referrer-Policy: "same-origin"
          Permissions-Policy: "geolocation=(), microphone=(), camera=()"
          Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self'"

    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

    nextcloud-security:
      chain:
        middlewares:
          - crowdsec-bouncer
          - rate-limit
          - nextcloud-headers

    root-security:
      chain:
        middlewares:
          - crowdsec-bouncer
          - rate-limit
          - root-headers
          - https-redirect
