---
source: file
filenames:
  - /var/log/traefik/access.log
labels:
  type: traefik

---
source: file
filenames:
  - /var/log/traefik/traefik.log
labels:
  type: traefik-error

---
source: docker
container_name:
  - traefik
labels:
  type: docker-traefik