---
services:
  postgres:
    image: postgres:17.5-alpine3.22
    container_name: postgres
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    networks: [proxy]
    ports: ["5432:5432"]
    environment:
      TZ: ${TZ}
      PGDATA: ${PGDATA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./conf/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./conf/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro

volumes:
  pgdata:
    external: true

networks:
  proxy:
    external: true